// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhqVao3DBlCWbuIIBAJcv5KGAtW7yePXo',
    appId: '1:849849366906:web:17b67019b120aba5a7fec3',
    messagingSenderId: '849849366906',
    projectId: 'zfft-dd773',
    authDomain: 'zfft-dd773.firebaseapp.com',
    storageBucket: 'zfft-dd773.firebasestorage.app',
    measurementId: 'G-JXZNXE8MZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_pXD5vRlSein-pgajbi6N0tdaSi-DfKE',
    appId: '1:849849366906:android:eadd6b1ed9e5df02a7fec3',
    messagingSenderId: '849849366906',
    projectId: 'zfft-dd773',
    storageBucket: 'zfft-dd773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCEalx2P_I6ikxCDmc_4tc6FISXLGLRg',
    appId: '1:849849366906:ios:dfb8d5179eb0e2f9a7fec3',
    messagingSenderId: '849849366906',
    projectId: 'zfft-dd773',
    storageBucket: 'zfft-dd773.firebasestorage.app',
    iosBundleId: 'com.example.zfffft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABCEalx2P_I6ikxCDmc_4tc6FISXLGLRg',
    appId: '1:849849366906:ios:0fd858801f9a8358a7fec3',
    messagingSenderId: '849849366906',
    projectId: 'zfft-dd773',
    storageBucket: 'zfft-dd773.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhqVao3DBlCWbuIIBAJcv5KGAtW7yePXo',
    appId: '1:849849366906:web:e6a2bfeb28f24595a7fec3',
    messagingSenderId: '849849366906',
    projectId: 'zfft-dd773',
    authDomain: 'zfft-dd773.firebaseapp.com',
    storageBucket: 'zfft-dd773.firebasestorage.app',
    measurementId: 'G-KTQ6SGQFMR',
  );
}
